### ISSUE TITLE
Module directory messed up

### ISSUE THREAD

**Issue by jamestrew** [trewjames/honorable-sudoku#6]
e.g.  
 ```
File "\honorable-sudoku\Pages\game_configure.py", line 1, in <module>
    from resource import *
ModuleNotFoundError: No module named 'resource'
```

I think `from MVC.View.view import View` in `widget_display.py` also has similar issues. I forget.

App runs regardless (kinda confusing to me why)

**Comment by mineugene** [comment]
Can you try renaming `resource.py` to another name, like `stylesheet.py` and updating all the `import resource` lines to see if it's a Windows issue?

Edit: I am not getting `ModuleNotFoundError` on my end.

**Comment by mineugene** [comment]
My console output preview using just the Windows command prompt.
```
$>python sudoku.py
[Debug] Puzzle loaded: gamemode(0), difficulty(0)

Process finished with exit code 0
```

**Comment by jamestrew** [comment]
Yeah I guess running sudoku.py doesn't raise any errors.
Running all the other scripts individually does. But I guess that's normal?

**Comment by mineugene** [comment]
Yeah, all the imports are setup to assume that `/honorable-sudoku` directory is the root.
A new constant can be setup in `resource.py` to get the absolute path to the project directory using the `os` library. Then change the imports to use that constant instead of the assumed project directory.

**Comment by mineugene** [comment]
Currently, `WidgetDisplay` and all of its child classes do not have a fallback implementation for when a handle instance is not given (no ref to Controller). So the behaviour right now is undefined when running it as __main__.
