### ISSUE TITLE
Unable to clear a cell once value inputted

### ISSUE THREAD

**Issue by jamestrew** [trewjames/honorable-sudoku#9]
Can only overwrite a cell, not clear.
Maybe bind del, backspace to clear a cell.

**Comment by mineugene** [comment]
Pressing zero should clear the cell.
a7e36ce shows the use of string.digits which includes the <0> key event. The cell clearing method is located in Pages.Game.grid_manager.py
```
line 31: self.foreground(x, y).config(text=(val if val>0 else ""))
```
